import random

#mad libs
#for now 3 random madlibs

print ('Welcome to mad libs!')
print ('lets get started!')
random = random.randint(1, 3)
if random == 1:
    print ('please put in a name')
    name = input()
    print ('please put in a verb')
    verb = input()
    print ('please enter in a noun')
    noun = input()
    print ('please put in a adverb')
    adverb = input()
    print (name + ' went out on a walk tuseday.')
    print ('But he ' + verb + ' intsed of walking.')
    print ('he love to do that!')
    print ('he love to play ' + noun + '.')
    print ('It was his favrit thing to do.')
    print ('You look ' + adverb + ' today!')
    print('================================')
    print ('     end')

if random == 2:
    print ('please put in a name')
    name = input()
    print ('please put in a verb')
    verb = input()
    print ('please enter in a noun')
    noun = input()
    print ('please put in a adverb')
    adverb = input()
    print (name + ' owns a pizza place.')
    print ('But he ' + verb + ' out of pizza sace.')
    print ('He hade to go buy more!')
    print ('He loved to make pizza at his pizza store named ' + noun + '.')
    print ('It was his favrit thing to do.')
    print ('He look ' + adverb + ' today!')
    print('================================')
    print ('      end')

if random == 3:
    print ('please put in a name')
    name = input()
    print ('please put in a verb')
    verb = input()
    print ('please enter in a noun')
    noun = input()
    print ('please put in a adverb')
    adverb = input()
    print (name + ' loved to talk.')
    print ('But he ' + verb + ' intsed of talking.')
    print ('he loved to play ball!')
    print ('he wanted to open a ' + noun + '.')
    print ('It was his dream!')
    print ('You look ' + adverb + ' yesterday!')
    print('================================')
    print ('      end')
